// Code generated by go-bindata. DO NOT EDIT.
// sources:
// datasource/migrations/1569651540_users.down.sql (19B)
// datasource/migrations/1569651540_users.up.sql (247B)
// datasource/migrations/1569658812_games.down.sql (19B)
// datasource/migrations/1569658812_games.up.sql (172B)
// datasource/migrations/1569658821_players.down.sql (21B)
// datasource/migrations/1569658821_players.up.sql (107B)
// datasource/migrations/1569658839_user_games.down.sql (23B)
// datasource/migrations/1569658839_user_games.up.sql (163B)
// datasource/migrations/1569659226_game_stats.down.sql (53B)
// datasource/migrations/1569659226_game_stats.up.sql (217B)

package migrationData

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes  []byte
	info   os.FileInfo
	digest [sha256.Size]byte
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __1569651540_usersDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x50\x2a\x2d\x4e\x2d\x2a\x56\xb2\x06\x04\x00\x00\xff\xff\xc2\x23\x41\xc8\x13\x00\x00\x00")

func _1569651540_usersDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569651540_usersDownSql,
		"1569651540_users.down.sql",
	)
}

func _1569651540_usersDownSql() (*asset, error) {
	bytes, err := _1569651540_usersDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569651540_users.down.sql", size: 19, mode: os.FileMode(0666), modTime: time.Unix(1569652184, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x3e, 0x16, 0xef, 0x60, 0x8a, 0x67, 0x69, 0x63, 0x7d, 0xcd, 0x2d, 0x38, 0xad, 0xc3, 0x7f, 0x3c, 0xd8, 0xfb, 0xeb, 0x6a, 0xfd, 0xf9, 0x41, 0x2c, 0x23, 0x70, 0x29, 0x6, 0x9a, 0xf6, 0xaa, 0xef}}
	return a, nil
}

var __1569651540_usersUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\xce\x31\x6b\x84\x30\x18\xc6\xf1\x5d\xf0\x3b\x3c\x38\x29\x74\xe8\xd0\xad\x93\x6d\x33\x48\xad\x6d\xc5\x0c\x4e\xf2\x6a\x5e\x68\xc0\xc4\x90\xc4\x16\xbf\x7d\x91\xf3\x0e\xee\x6e\x7e\x7e\x7f\x78\x5e\x5b\x51\x76\x02\x5d\xf9\x52\x0b\x64\x6b\x60\x1f\x32\xe4\x69\x02\x00\x5a\x41\xca\xea\x0d\xcd\x67\x87\x46\xd6\x35\xbe\xda\xea\xa3\x6c\x7b\xbc\x8b\xfe\xe1\x44\xf6\xc0\x92\x61\xfc\x92\x9f\x7e\xc8\xe7\x4f\x8f\x05\x64\x53\x7d\x4b\x71\xc9\x0e\xca\x86\xf4\x7c\xe5\x6e\x81\x9d\xfc\xe6\x22\xab\xc1\x51\x08\x7f\x8b\x57\x18\xb7\xc8\x74\xcc\x61\x75\xec\x07\x52\x46\x5b\x8c\xcb\x32\x33\xd9\x63\x99\x3c\xd3\x9e\x51\x44\xd4\x86\x43\x24\xe3\xce\xff\x9c\xba\x9b\xd2\xa4\x78\xfe\x0f\x00\x00\xff\xff\x53\x8c\x3e\x4e\xf7\x00\x00\x00")

func _1569651540_usersUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569651540_usersUpSql,
		"1569651540_users.up.sql",
	)
}

func _1569651540_usersUpSql() (*asset, error) {
	bytes, err := _1569651540_usersUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569651540_users.up.sql", size: 247, mode: os.FileMode(0666), modTime: time.Unix(1569658229, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x89, 0x1b, 0x22, 0x2d, 0x63, 0xd5, 0x23, 0x13, 0x59, 0x9f, 0x4e, 0xff, 0xc, 0x81, 0x8c, 0x41, 0x65, 0xf7, 0x32, 0x6, 0x93, 0x70, 0x48, 0xe1, 0x26, 0x42, 0xaa, 0xe2, 0xea, 0x21, 0x41, 0x19}}
	return a, nil
}

var __1569658812_gamesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x50\x4a\x4f\xcc\x4d\x2d\x56\xb2\x06\x04\x00\x00\xff\xff\x52\x29\xa0\x8b\x13\x00\x00\x00")

func _1569658812_gamesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658812_gamesDownSql,
		"1569658812_games.down.sql",
	)
}

func _1569658812_gamesDownSql() (*asset, error) {
	bytes, err := _1569658812_gamesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658812_games.down.sql", size: 19, mode: os.FileMode(0666), modTime: time.Unix(1569658998, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x3b, 0xaf, 0x8c, 0x2b, 0xe6, 0xc8, 0x89, 0x12, 0xf5, 0x86, 0xde, 0xf5, 0x4c, 0x56, 0xe2, 0x7e, 0x40, 0x7f, 0x7c, 0xb1, 0x93, 0xdd, 0xed, 0xf7, 0x4c, 0xf5, 0x40, 0xcb, 0x44, 0xfb, 0xe5, 0x3e}}
	return a, nil
}

var __1569658812_gamesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\x50\x4a\x4f\xcc\x4d\x2d\x56\x52\xd0\xe0\xe5\x52\x00\x81\xcc\x14\x85\xd0\x50\x4f\x17\x05\x3f\xff\x10\x05\xbf\x50\x1f\x1f\x85\x80\x20\x4f\x5f\xc7\xa0\x48\x05\x6f\xd7\x48\x1d\xa8\x9a\xbc\xc4\xdc\x54\x85\x92\xd4\x8a\x12\xb8\x2a\x98\x4c\x71\x6a\x72\x51\x6a\x89\x42\x52\x65\x49\x6a\x22\x86\x64\x72\x51\x6a\x62\x49\x6a\x4a\x7c\x62\x89\x42\x49\x66\x6e\x6a\x71\x49\x62\x6e\x01\x4c\xae\xb4\x20\x05\x43\x8e\x97\x4b\xd3\x1a\x10\x00\x00\xff\xff\x93\x6f\x09\x3b\xac\x00\x00\x00")

func _1569658812_gamesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658812_gamesUpSql,
		"1569658812_games.up.sql",
	)
}

func _1569658812_gamesUpSql() (*asset, error) {
	bytes, err := _1569658812_gamesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658812_games.up.sql", size: 172, mode: os.FileMode(0666), modTime: time.Unix(1569659070, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xfa, 0xed, 0x1e, 0xde, 0xaa, 0xe7, 0x10, 0x18, 0x1, 0x5f, 0x84, 0x1a, 0x66, 0xe1, 0x62, 0x28, 0x7c, 0xc0, 0x26, 0x48, 0x8, 0x34, 0xa6, 0xf8, 0xee, 0xed, 0x2b, 0x73, 0x3, 0x24, 0xc5, 0xf4}}
	return a, nil
}

var __1569658821_playersDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x50\x2a\xc8\x49\xac\x4c\x2d\x2a\x56\xb2\x06\x04\x00\x00\xff\xff\xe4\xb2\x6b\x27\x15\x00\x00\x00")

func _1569658821_playersDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658821_playersDownSql,
		"1569658821_players.down.sql",
	)
}

func _1569658821_playersDownSql() (*asset, error) {
	bytes, err := _1569658821_playersDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658821_players.down.sql", size: 21, mode: os.FileMode(0666), modTime: time.Unix(1569659096, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x8f, 0x84, 0xe, 0x4b, 0x93, 0xea, 0x64, 0xf1, 0x62, 0x1c, 0x74, 0xea, 0x1, 0x53, 0x4d, 0x4e, 0x19, 0x2f, 0xd2, 0xdd, 0xca, 0xe5, 0x5b, 0x80, 0x4c, 0x22, 0xb9, 0x8, 0x4d, 0xc9, 0xfb, 0xf4}}
	return a, nil
}

var __1569658821_playersUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\x50\x2a\xc8\x49\xac\x4c\x2d\x2a\x56\x52\xd0\xe0\xe5\x52\xc8\x4c\x51\x08\x0d\xf5\x74\x51\xf0\xf3\x0f\x51\xf0\x0b\xf5\xf1\x51\x08\x08\xf2\xf4\x75\x0c\x8a\x54\xf0\x76\x8d\xd4\xe1\xe5\x52\x48\xcd\x4d\xcc\xcc\xc9\x48\x2c\xce\x50\x48\xaa\x2c\x49\x4d\x54\x08\xf5\xf3\x0c\x0c\x75\x85\x2b\x07\x29\xc9\x4b\xcc\x4d\x55\x28\x49\xad\x28\xe1\xe5\xd2\xb4\x06\x04\x00\x00\xff\xff\x76\xc6\x29\xf5\x6b\x00\x00\x00")

func _1569658821_playersUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658821_playersUpSql,
		"1569658821_players.up.sql",
	)
}

func _1569658821_playersUpSql() (*asset, error) {
	bytes, err := _1569658821_playersUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658821_players.up.sql", size: 107, mode: os.FileMode(0666), modTime: time.Unix(1569659389, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x49, 0x2f, 0x6d, 0x33, 0x9b, 0x3b, 0x84, 0xe6, 0x11, 0x5f, 0x4a, 0x83, 0x7f, 0x94, 0xcd, 0xd, 0xf7, 0x0, 0xaa, 0x1b, 0xb8, 0xb2, 0x4c, 0x38, 0xb7, 0xdf, 0x37, 0x3e, 0x94, 0xd1, 0x36, 0xc2}}
	return a, nil
}

var __1569658839_user_gamesDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x50\x2a\x2d\x4e\x2d\x8a\x4f\x4f\xcc\x4d\x55\xb2\x06\x04\x00\x00\xff\xff\xa2\xa3\x14\x0f\x17\x00\x00\x00")

func _1569658839_user_gamesDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658839_user_gamesDownSql,
		"1569658839_user_games.down.sql",
	)
}

func _1569658839_user_gamesDownSql() (*asset, error) {
	bytes, err := _1569658839_user_gamesDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658839_user_games.down.sql", size: 23, mode: os.FileMode(0666), modTime: time.Unix(1569659193, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0xe0, 0xe7, 0x16, 0x6a, 0x70, 0x5f, 0x30, 0x4b, 0xce, 0x23, 0xea, 0x71, 0x1d, 0xac, 0x7, 0xb4, 0xde, 0xfb, 0x11, 0x48, 0x21, 0xbf, 0xc9, 0xa4, 0xa2, 0x2b, 0xb5, 0xda, 0xa9, 0xcb, 0xf3, 0x62}}
	return a, nil
}

var __1569658839_user_gamesUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x0e\x72\x75\x0c\x71\x55\x08\x71\x74\xf2\x71\x55\x50\x2a\x2d\x4e\x2d\x8a\x4f\x4f\xcc\x4d\x55\x52\xd0\xe0\xe5\x52\x50\x50\x50\x00\x8b\x64\xa6\x28\x84\x86\x7a\xba\x28\xf8\xf9\x87\x28\xf8\x85\xfa\xf8\x28\x14\xa5\xa6\xa5\x16\xa5\xe6\x25\xa7\x16\x83\x15\x14\x6b\x64\xa6\x68\xea\x40\x34\x80\x74\xe3\xd5\x00\x52\x80\xac\x21\x20\xc8\xd3\xd7\x31\x28\x52\xc1\xdb\x35\x52\x03\x6a\x9b\x0e\xcc\x14\x4d\x5e\x2e\x4d\x6b\x40\x00\x00\x00\xff\xff\xc2\xf9\xf9\xbd\xa3\x00\x00\x00")

func _1569658839_user_gamesUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569658839_user_gamesUpSql,
		"1569658839_user_games.up.sql",
	)
}

func _1569658839_user_gamesUpSql() (*asset, error) {
	bytes, err := _1569658839_user_gamesUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569658839_user_games.up.sql", size: 163, mode: os.FileMode(0666), modTime: time.Unix(1569659669, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x2e, 0xd6, 0x90, 0x52, 0x6f, 0x9a, 0x4a, 0xa8, 0x7a, 0x36, 0x27, 0xac, 0xbd, 0x80, 0x57, 0x72, 0x51, 0xe5, 0x82, 0xf1, 0x8a, 0x15, 0x97, 0xbe, 0x4f, 0xa8, 0xd1, 0xb7, 0xa6, 0xc7, 0xdc, 0x2e}}
	return a, nil
}

var __1569659226_game_statsDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\x50\x4a\x4f\xcc\x4d\x8d\x2f\x2e\x49\x2c\x29\x56\xb2\xe6\xe5\x82\xc8\x44\x06\x20\x4b\xc4\x97\x54\x16\xa4\x2a\x59\x03\x02\x00\x00\xff\xff\x4b\x52\x0f\x24\x35\x00\x00\x00")

func _1569659226_game_statsDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569659226_game_statsDownSql,
		"1569659226_game_stats.down.sql",
	)
}

func _1569659226_game_statsDownSql() (*asset, error) {
	bytes, err := _1569659226_game_statsDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569659226_game_stats.down.sql", size: 53, mode: os.FileMode(0666), modTime: time.Unix(1569659489, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x54, 0xaf, 0xf3, 0xe3, 0xde, 0xc, 0x8a, 0x6f, 0xc8, 0x66, 0x5e, 0x51, 0x9, 0xda, 0x9c, 0x69, 0xec, 0xa1, 0xb0, 0xea, 0x54, 0x87, 0xd9, 0x71, 0x98, 0xbb, 0x93, 0xa1, 0xb1, 0xdc, 0xdd, 0xff}}
	return a, nil
}

var __1569659226_game_statsUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x64\xce\x31\x0f\x82\x30\x10\x05\xe0\xbd\x49\xff\xc3\x0b\x4b\x21\xe1\x1f\x30\x55\xed\x40\x04\x24\x48\x07\x26\x42\xe0\x34\x0c\xa0\x69\x6f\xd0\x7f\x6f\xc0\xc0\xa0\xeb\xdd\xf7\xf2\xde\xb1\x32\xba\x36\xa8\x9b\xd2\xe0\xde\x4d\xd4\x7a\xee\xb8\xe5\xf7\x93\xa0\xaf\x30\x85\xcd\x11\x2a\xdf\x3f\x1c\xa9\x18\x8a\xc7\x89\x54\x94\x48\xb1\xc5\xf4\x21\x33\x08\xf6\xa0\x0f\x10\x4a\x81\x71\x80\xb5\xe9\x09\xc5\xa5\x46\x61\xb3\x0c\x65\x95\xe6\xba\x6a\x70\x36\x4d\x2c\xc5\xb7\xe8\x0f\x39\xba\x91\xa3\xb9\x27\xbf\x02\x1f\x8e\x43\xb4\xe8\xb9\x9b\x08\x4c\x2f\xde\xe9\x72\x5d\x27\xfe\x2c\xde\xfe\x52\x44\xc9\x27\x00\x00\xff\xff\xb6\x66\x74\x71\xd9\x00\x00\x00")

func _1569659226_game_statsUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__1569659226_game_statsUpSql,
		"1569659226_game_stats.up.sql",
	)
}

func _1569659226_game_statsUpSql() (*asset, error) {
	bytes, err := _1569659226_game_statsUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "1569659226_game_stats.up.sql", size: 217, mode: os.FileMode(0666), modTime: time.Unix(1569659677, 0)}
	a := &asset{bytes: bytes, info: info, digest: [32]uint8{0x6e, 0x14, 0x78, 0x97, 0x57, 0xbc, 0x37, 0x59, 0xeb, 0x4f, 0x90, 0x92, 0x2e, 0x8d, 0xc, 0x47, 0x7f, 0xc2, 0x15, 0x6d, 0xdd, 0xcc, 0x46, 0x40, 0xdd, 0xc, 0xc6, 0x69, 0xcc, 0xaf, 0x96, 0x9b}}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// AssetString returns the asset contents as a string (instead of a []byte).
func AssetString(name string) (string, error) {
	data, err := Asset(name)
	return string(data), err
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// MustAssetString is like AssetString but panics when Asset would return an
// error. It simplifies safe initialization of global variables.
func MustAssetString(name string) string {
	return string(MustAsset(name))
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetDigest returns the digest of the file with the given name. It returns an
// error if the asset could not be found or the digest could not be loaded.
func AssetDigest(name string) ([sha256.Size]byte, error) {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[canonicalName]; ok {
		a, err := f()
		if err != nil {
			return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s can't read by error: %v", name, err)
		}
		return a.digest, nil
	}
	return [sha256.Size]byte{}, fmt.Errorf("AssetDigest %s not found", name)
}

// Digests returns a map of all known files and their checksums.
func Digests() (map[string][sha256.Size]byte, error) {
	mp := make(map[string][sha256.Size]byte, len(_bindata))
	for name := range _bindata {
		a, err := _bindata[name]()
		if err != nil {
			return nil, err
		}
		mp[name] = a.digest
	}
	return mp, nil
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"1569651540_users.down.sql": _1569651540_usersDownSql,

	"1569651540_users.up.sql": _1569651540_usersUpSql,

	"1569658812_games.down.sql": _1569658812_gamesDownSql,

	"1569658812_games.up.sql": _1569658812_gamesUpSql,

	"1569658821_players.down.sql": _1569658821_playersDownSql,

	"1569658821_players.up.sql": _1569658821_playersUpSql,

	"1569658839_user_games.down.sql": _1569658839_user_gamesDownSql,

	"1569658839_user_games.up.sql": _1569658839_user_gamesUpSql,

	"1569659226_game_stats.down.sql": _1569659226_game_statsDownSql,

	"1569659226_game_stats.up.sql": _1569659226_game_statsUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"},
// AssetDir("data/img") would return []string{"a.png", "b.png"},
// AssetDir("foo.txt") and AssetDir("notexist") would return an error, and
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		canonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(canonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}

var _bintree = &bintree{nil, map[string]*bintree{
	"1569651540_users.down.sql":      &bintree{_1569651540_usersDownSql, map[string]*bintree{}},
	"1569651540_users.up.sql":        &bintree{_1569651540_usersUpSql, map[string]*bintree{}},
	"1569658812_games.down.sql":      &bintree{_1569658812_gamesDownSql, map[string]*bintree{}},
	"1569658812_games.up.sql":        &bintree{_1569658812_gamesUpSql, map[string]*bintree{}},
	"1569658821_players.down.sql":    &bintree{_1569658821_playersDownSql, map[string]*bintree{}},
	"1569658821_players.up.sql":      &bintree{_1569658821_playersUpSql, map[string]*bintree{}},
	"1569658839_user_games.down.sql": &bintree{_1569658839_user_gamesDownSql, map[string]*bintree{}},
	"1569658839_user_games.up.sql":   &bintree{_1569658839_user_gamesUpSql, map[string]*bintree{}},
	"1569659226_game_stats.down.sql": &bintree{_1569659226_game_statsDownSql, map[string]*bintree{}},
	"1569659226_game_stats.up.sql":   &bintree{_1569659226_game_statsUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory.
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	return os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
}

// RestoreAssets restores an asset under the given directory recursively.
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	canonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(canonicalName, "/")...)...)
}
