// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

var TableNames = struct {
	GameStats string
	Games     string
	Players   string
	UserGame  string
	Users     string
}{
	GameStats: "game_stats",
	Games:     "games",
	Players:   "players",
	UserGame:  "user_game",
	Users:     "users",
}
