// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("GameStats", testGameStats)
	t.Run("Games", testGames)
	t.Run("Players", testPlayers)
	t.Run("UserGames", testUserGames)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("GameStats", testGameStatsDelete)
	t.Run("Games", testGamesDelete)
	t.Run("Players", testPlayersDelete)
	t.Run("UserGames", testUserGamesDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("GameStats", testGameStatsQueryDeleteAll)
	t.Run("Games", testGamesQueryDeleteAll)
	t.Run("Players", testPlayersQueryDeleteAll)
	t.Run("UserGames", testUserGamesQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("GameStats", testGameStatsSliceDeleteAll)
	t.Run("Games", testGamesSliceDeleteAll)
	t.Run("Players", testPlayersSliceDeleteAll)
	t.Run("UserGames", testUserGamesSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("GameStats", testGameStatsExists)
	t.Run("Games", testGamesExists)
	t.Run("Players", testPlayersExists)
	t.Run("UserGames", testUserGamesExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("GameStats", testGameStatsFind)
	t.Run("Games", testGamesFind)
	t.Run("Players", testPlayersFind)
	t.Run("UserGames", testUserGamesFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("GameStats", testGameStatsBind)
	t.Run("Games", testGamesBind)
	t.Run("Players", testPlayersBind)
	t.Run("UserGames", testUserGamesBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("GameStats", testGameStatsOne)
	t.Run("Games", testGamesOne)
	t.Run("Players", testPlayersOne)
	t.Run("UserGames", testUserGamesOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("GameStats", testGameStatsAll)
	t.Run("Games", testGamesAll)
	t.Run("Players", testPlayersAll)
	t.Run("UserGames", testUserGamesAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("GameStats", testGameStatsCount)
	t.Run("Games", testGamesCount)
	t.Run("Players", testPlayersCount)
	t.Run("UserGames", testUserGamesCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("GameStats", testGameStatsHooks)
	t.Run("Games", testGamesHooks)
	t.Run("Players", testPlayersHooks)
	t.Run("UserGames", testUserGamesHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("GameStats", testGameStatsInsert)
	t.Run("GameStats", testGameStatsInsertWhitelist)
	t.Run("Games", testGamesInsert)
	t.Run("Games", testGamesInsertWhitelist)
	t.Run("Players", testPlayersInsert)
	t.Run("Players", testPlayersInsertWhitelist)
	t.Run("UserGames", testUserGamesInsert)
	t.Run("UserGames", testUserGamesInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("GameStatToGameUsingGame", testGameStatToOneGameUsingGame)
	t.Run("UserGameToGameUsingGame", testUserGameToOneGameUsingGame)
	t.Run("UserGameToUserUsingUser", testUserGameToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("GameToGameStats", testGameToManyGameStats)
	t.Run("GameToUserGames", testGameToManyUserGames)
	t.Run("UserToUserGames", testUserToManyUserGames)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("GameStatToGameUsingGameStats", testGameStatToOneSetOpGameUsingGame)
	t.Run("UserGameToGameUsingUserGames", testUserGameToOneSetOpGameUsingGame)
	t.Run("UserGameToUserUsingUserGames", testUserGameToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("GameToGameStats", testGameToManyAddOpGameStats)
	t.Run("GameToUserGames", testGameToManyAddOpUserGames)
	t.Run("UserToUserGames", testUserToManyAddOpUserGames)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("GameStats", testGameStatsReload)
	t.Run("Games", testGamesReload)
	t.Run("Players", testPlayersReload)
	t.Run("UserGames", testUserGamesReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("GameStats", testGameStatsReloadAll)
	t.Run("Games", testGamesReloadAll)
	t.Run("Players", testPlayersReloadAll)
	t.Run("UserGames", testUserGamesReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("GameStats", testGameStatsSelect)
	t.Run("Games", testGamesSelect)
	t.Run("Players", testPlayersSelect)
	t.Run("UserGames", testUserGamesSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("GameStats", testGameStatsUpdate)
	t.Run("Games", testGamesUpdate)
	t.Run("Players", testPlayersUpdate)
	t.Run("UserGames", testUserGamesUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("GameStats", testGameStatsSliceUpdateAll)
	t.Run("Games", testGamesSliceUpdateAll)
	t.Run("Players", testPlayersSliceUpdateAll)
	t.Run("UserGames", testUserGamesSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
