// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodels_raw

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("GameStats", testGameStatsUpsert)

	t.Run("Games", testGamesUpsert)

	t.Run("Players", testPlayersUpsert)

	t.Run("UserGames", testUserGamesUpsert)

	t.Run("Users", testUsersUpsert)
}
